/**
 * FRONTEND INTERVIEW QUESTIONS & ANSWERS (500 Questions)
 * Ushbu ro'yxat React, JavaScript, HTML/CSS, TypeScript, Next.js va Frontend arxitekturasini qamrab oladi.
 */

export const frontendQuestions = [
  // --- Basics & Core (1-100) - Oldin yozilganlar saqlab qolindi ---
  { id: 1, question: "Virtual DOM nima?", answer: "Haqiqiy DOM-ning xotiradagi nusxasi. O'zgarishlarni tezroq hisoblash va faqat kerakli qismini yangilash uchun ishlatiladi." },
  { id: 2, question: "useState nima vazifani bajaradi?", answer: "Funktsional komponentlarda holatni (state) saqlash va yangilash uchun ishlatiladi." },
  // ... (1-100 savollar qisqartirildi, lekin faylda to'liq bo'ladi)
  { id: 100, question: "XSS va CSRF nima?", answer: "XSS - zararli script yuborish. CSRF - foydalanuvchi nomidan ruxsatsiz so'rov yuborish." },

  // --- Advanced & Pro (101-200) - Oldin yozilganlar ---
  { id: 101, question: "Tree Shaking nima?", answer: "Ishlatilmaydigan kodni paketdan (bundle) olib tashlash jarayoni." },
  // ... (101-200 savollar qisqartirildi)
  { id: 200, question: "State of Frontend 2024?", answer: "React, Vite, Next.js, TypeScript va Sun'iy intellekt trendlari." },

  // --- NEW: React 18/19 & Modern Hooks (201-230) ---
  { id: 201, question: "useTransition hook-i nima?", answer: "UI-ni bloklamasdan holatni yangilash imkonini beradi. Past ustuvorlikdagi yangilanishlarni belgilash uchun ishlatiladi." },
  { id: 202, question: "useDeferredValue vazifasi?", answer: "Qiymatning 'kechiktirilgan' nusxasini qaytaradi, bu esa og'ir UI komponentlarini render qilishni optimallashtiradi." },
  { id: 203, question: "useSyncExternalStore nima?", answer: "Tashqi store-lar (masalan, Redux, Zustand) bilan React Concurrent mode o'rtasida sinxronizatsiyani ta'minlaydi." },
  { id: 204, question: "React 18 'Automatic Batching' nima?", answer: "Sinxron, asinxron (Promise, setTimeout) barcha state o'zgarishlarini bitta renderga guruhlash." },
  { id: 205, question: "Suspense for Data Fetching qanday ishlaydi?", answer: "Ma'lumot yuklanayotgan vaqtda 'fallback' UI ko'rsatishni deklarativ boshqarish." },
  { id: 206, question: "React 19 'use' hook-i nima?", answer: "Context yoki Promiselarni to'g'ridan-to'g'ri render ichida o'qish imkonini beruvchi yangi hook." },
  { id: 207, question: "Server Actions nima (React 19/Next.js)?", answer: "Mijoz tomonidan to'g'ridan-to'g'ri serverdagi funktsiyalarni chaqirish imkoniyati (form submission uchun qulay)." },
  { id: 208, question: "Optimistic UI React 19-da qanday qilinadi?", answer: "useOptimistic hook-i orqali server javobini kutmasdan UI-ni yangilash." },
  { id: 209, question: "Document Metadata (React 19)?", answer: "Title, Meta teglarni endi istalgan komponent ichida deklarativ yozish imkoniyati." },
  { id: 210, question: "React Compiler (Forget) nima?", answer: "useMemo va useCallback-ni avtomatlashtiruvchi yangi React komplyatori." },
  { id: 211, question: "Hydration Overlay nima?", answer: "Hydration xatolarini vizual ko'rsatuvchi vosita." },
  { id: 212, question: "React context-da 'Selector' muammosi nima?", answer: "Context-dagi bitta qiymat o'zgarsa, undan foydalanuvchi barcha komponentlar qayta render bo'lishi." },
  { id: 213, question: "React.lazy va dynamic import farqi?", answer: "React.lazy faqat komponentlar uchun, dynamic import esa ixtiyoriy JS moduli uchun." },
  { id: 214, question: "Error Boundary class bo'lishi shartmi?", answer: "Hozircha ha, Reactda Error Boundary uchun hali maxsus hook yo'q." },
  { id: 215, question: "Portal-da event bubbling ishlaydimi?", answer: "Ha, garchi DOM-da boshqa joyda bo'lsa ham, React daraxtida event yuqoriga chiqadi." },
  { id: 216, question: "React-da 'Effect Cleanup' nega kerak?", answer: "Memory leak va ortiqcha network requestlarni oldini olish uchun (masalan, socket yopish)." },
  { id: 217, question: "Ref forwarding qachon kerak?", answer: "UI kutubxonalar yaratishda child elementga to'g'ridan-to'g'ri kirish berish uchun." },
  { id: 218, question: "ImperativeHandle hook-i nima?", answer: "Parent komponentga child komponent ichidagi xususiy metodlarni ochib berish." },
  { id: 219, question: "React 'Strict Mode' ishlab chiqarishda ishlaydimi?", answer: "Yo'q, u faqat development vaqtida xatolarni topishga yordam beradi." },
  { id: 220, question: "Key prop sifatida index ishlatish qachon xavfsiz?", answer: "Ro'yxat o'zgarmas (static) bo'lganda va filtrlanmaganda." },
  { id: 221, question: "React-da renderlash qachon trigger bo'ladi?", answer: "State o'zgarganda, Parent render bo'lganda, Context o'zgarganda, Force update bo'lganda." },
  { id: 222, question: "React.memo-ning ikkinchi argumenti nima?", answer: "Oldingi va yangi proplarni solishtirish funktsiyasi (areEqual)." },
  { id: 223, question: "State vs Ref qachon qaysini tanlash kerak?", answer: "Renderga ta'sir qiluvchi ma'lumot uchun State, ta'sir qilmaydigan (hidden) ma'lumot uchun Ref." },
  { id: 224, question: "React-da 'Prop-types' nima?", answer: "TypeScript-dan oldin proplarni tekshirish uchun ishlatilgan kutubxona." },
  { id: 225, question: "React-da 'Controlled component' xususiyati?", answer: "Input qiymati har doim React 'Source of truth' (state) bilan bog'langan bo'ladi." },
  { id: 226, question: "Next.js 'Image' komponenti afzalligi?", answer: "Lazy loading, avtomatik format o'zgartirish (WebP), o'lchamni optimallashtirish." },
  { id: 227, question: "Next.js 'Font' optimizatsiyasi?", answer: "Google fontlarni o'z serveringizga yuklab, Layout shiftni oldini oladi." },
  { id: 228, question: "React-da 'Compound components' misoli?", answer: "Select va Select.Option komponentlarining bog'liqligi." },
  { id: 229, question: "React-da 'Higher-order hooks' bormi?", answer: "Yo'q, hooklarni shartli yoki loop ichida ishlatib bo'lmaydi." },
  { id: 230, question: "State management-da 'Flux' arxitekturasi nima?", answer: "Ma'lumotlarning bir tomonlama oqimi (Action -> Dispatcher -> Store -> View)." },

  // --- TypeScript Deep Dive (231-270) ---
  { id: 231, question: "TS 'Mapped Types' nima?", answer: "Mavjud turdagi barcha kalitlarni o'zgartirib yangi tur hosil qilish." },
  { id: 232, question: "TS 'Conditional Types' nima?", answer: "Turdagi 'if/else' mantiqi: T extends U ? X : Y." },
  { id: 233, question: "TS 'Template Literal Types' nima?", answer: "Stringlarni birlashtirib murakkab turlar yasash (masalan: `padding-${'top' | 'bottom'}`)." },
  { id: 234, question: "TS 'Discriminated Unions' nima?", answer: "Umumiy 'kind' yoki 'type' maydoni orqali turlarni aniq ajratish." },
  { id: 235, question: "TS 'Inference' nima?", answer: "TypeScript-ning qiymatga qarab turini avtomatik aniqlashi." },
  { id: 236, question: "TS 'Declaration Merging' nima?", answer: "Ikkita bir xil nomli interfeysning xususiyatlari birlashib ketishi." },
  { id: 237, question: "TS 'Ambient Modules' nima?", answer: ".d.ts fayllar orqali tashqi kutubxonalarga tur e'lon qilish." },
  { id: 238, question: "TS 'Utility Types': Record<K, T> nima?", answer: "Kalitlari K turi, qiymatlari T turi bo'lgan ob'ekt turi." },
  { id: 239, question: "TS 'Satisfies' operatori (v4.9+)?", answer: "Ob'ektning ma'lum turga mosligini tekshiradi, lekin uning aniq turini o'zgartirmaydi." },
  { id: 240, question: "TS 'Branded Types' nima?", answer: "Oddiy string yoki number-larni bir-biridan ajratish uchun ishlatiladigan 'soxta' turlar." },
  { id: 241, question: "TS 'Keyof' operatori?", answer: "Ob'ektning barcha kalitlarini union turi sifatida qaytaradi." },
  { id: 242, question: "TS 'Typeof' operatori?", answer: "O'zgaruvchining turini olish uchun ishlatiladi." },
  { id: 243, question: "TS 'Extract' vs 'Exclude'?", answer: "Exclude - keraksiz tur bo'laklarini olib tashlaydi. Extract - keraklisini oladi." },
  { id: 244, question: "TS 'NonNullable' nima?", answer: "Turdagi null va undefined qiymatlarni olib tashlaydi." },
  { id: 245, question: "TS 'Parameters' va 'ReturnType'?", answer: "Funktsiyaning argumentlari yoki qaytarish turini olish." },
  { id: 246, question: "TS 'Enum' vs 'Const Enum'?", answer: "Const enum JS kodiga o'tmaydi (inline qilinadi), xotirani tejaydi." },
  { id: 247, question: "TS 'Module Resolution' nima?", answer: "TS-ning import qilingan faylni qayerdan qidirish tartibi (Classic vs Node)." },
  { id: 248, question: "TS 'Namespace' nima?", answer: "Kodlarni guruhlash uchun eski usul (hozirda ESM modullari tavsiya etiladi)." },
  { id: 249, question: "TS 'Decorator' nima?", answer: "Class, metod yoki xususiyatga qo'shimcha mantiq qo'shish (hali experimental)." },
  { id: 250, question: "TS 'Type Guards' (is operatori)?", answer: "Funktsiya qaytarayotgan qiymatni aniq turga ega ekanini tasdiqlash." },
  { id: 251, question: "TS 'Awaited' turi?", answer: "Promise ichidagi yakuniy qiymat turini olish." },
  { id: 252, question: "TS 'ReadonlyArray' afzalligi?", answer: "Massiv elementlarini o'zgartirishni (push, pop) taqiqlash." },
  { id: 253, question: "TS 'Indexed Access Types'?", answer: "T[K] ko'rinishida ob'ektning ma'lum xususiyati turini olish." },
  { id: 254, question: "TS 'Assertion Functions'?", answer: "Shart bajarilmasa xato tashlaydigan va turini tasdiqlaydigan funktsiyalar." },
  { id: 255, question: "TS-da 'Nullish Coalescing' (??)?", answer: "Faqat null yoki undefined bo'lganda ishlaydigan operator." },
  { id: 256, question: "TS 'Optional Chaining' (?.)?", answer: "Ob'ekt xususiyati mavjudligini xavfsiz tekshirib o'tish." },
  { id: 257, question: "TS 'StrictNullChecks' nega muhim?", answer: "Dasturda 'null pointer exception' xatolarini 90% kamaytiradi." },
  { id: 258, question: "TS-da 'as const' nima qiladi?", answer: "O'zgaruvchini 'literal readonly' turiga o'tkazadi." },
  { id: 259, question: "TS 'Intersection Types' (&)?", answer: "Ikki yoki undan ko'p turlarni birlashtirib yangi tur hosil qilish." },
  { id: 260, question: "TS-da 'Void' va 'Never' farqi?", answer: "Void - natija yo'q (lekin tugaydi). Never - hech qachon tugamaydi yoki xato." },
  { id: 261, question: "TS 'ConstructorParameters' nima?", answer: "Class konstruktorining argumentlari turini olish." },
  { id: 262, question: "TS 'InstanceType' nima?", answer: "Class-dan yaratilgan ob'ekt turini olish." },
  { id: 263, question: "TS 'Partial' vs 'Required'?", answer: "Partial hamma xususiyatni ixtiyoriy qiladi, Required majburiy." },
  { id: 264, question: "TS 'Pick' vs 'Omit'?", answer: "Pick keraklisini tanlaydi, Omit keraksizini tashlaydi." },
  { id: 265, question: "TS 'NoImplicitAny' sozlamasi?", answer: "Agar tur ko'rsatilmadi va TS aniqlay olmasa xato ko'rsatish." },
  { id: 266, question: "TS 'Target' vs 'Lib' sozlamalari?", answer: "Target - qaysi JS versiyasiga o'tkazish. Lib - qaysi muhit (DOM, ES2020) kutubxonalarini tanish." },
  { id: 267, question: "TS 'Incremental Compilation'?", answer: "Faqat o'zgargan fayllarni qayta kompilyatsiya qilib vaqtni tejash." },
  { id: 268, question: "TS 'Downlevel Iteration'?", answer: "Eski JS versiyalarida for-of kabi looplarni to'g'ri ishlashini ta'minlash." },
  { id: 269, question: "TS 'Decorator Metadata' nima?", answer: "Run-time vaqtida turlar haqida ma'lumot olish imkoniyati." },
  { id: 270, question: "TS 'ModuleSuffixes' (v4.7+)?", answer: "Turli muhitlar (.ios.ts, .android.ts) uchun fayllarni ajratish." },

  // --- Next.js & Modern Web Architecture (271-310) ---
  { id: 271, question: "Next.js 'App Router' vs 'Pages Router'?", answer: "App Router - React Server Components va yangi Layout tizimiga asoslangan." },
  { id: 272, question: "Static Site Generation (SSG) qachon kerak?", answer: "Ma'lumotlar kam o'zgarganda (Blog, Documentation)." },
  { id: 273, question: "Incremental Static Regeneration (ISR) nima?", answer: "Statik sahifalarni fon rejimida, ma'lum vaqtdan keyin yangilab borish." },
  { id: 274, question: "Next.js 'Parallel Routes' nima?", answer: "Bitta sahifada bir vaqtda bir nechta 'slot' (dashboard qismlari) ko'rsatish." },
  { id: 275, question: "Next.js 'Intercepting Routes' nima?", answer: "Bir sahifa ichida boshqa sahifani (masalan modalda) 'tutib olish'." },
  { id: 276, question: "Next.js 'Server Components' cheklovlari?", answer: "useEffect, useState ishlatib bo'lmaydi, DOM-ga to'g'ridan-to'g'ri kirib bo'lmaydi." },
  { id: 277, question: "Client Components ('use client') qachon ishlatiladi?", answer: "Interaktivlik (button click), hooklar, brauzer API-lari kerak bo'lganda." },
  { id: 278, question: "Next.js 'Dynamic IO' nima?", answer: "Keshni avtomatik va aqlli boshqarish mexanizmi." },
  { id: 279, question: "Edge Runtime nima?", answer: "Kodni foydalanuvchiga yaqin bo'lgan CDN serverlarida (Global) ishga tushirish." },
  { id: 280, question: "Next.js 'Middleware' cheklovlari?", answer: "Faqat Edge runtime-da ishlaydi, Node.js API-laridan to'liq foydalanib bo'lmaydi." },
  { id: 281, question: "SEO: Canonical link nima?", answer: "Dublikat sahifalardan asosiysini qidiruv tizimiga ko'rsatish." },
  { id: 282, question: "SEO: Robots.txt nima?", answer: "Qidiruv botlariga qaysi sahifalarni indekslashni taqiqlash yoki ruxsat berish." },
  { id: 283, question: "SEO: Sitemap.xml nima?", answer: "Saytning barcha URL-lari ro'yxati (indekslashni tezlashtiradi)." },
  { id: 284, question: "Web Performance: TBT (Total Blocking Time) nima?", answer: "Asosiy oqim (Main thread) bloklangan jami vaqt." },
  { id: 285, question: "Web Performance: LCP optimallashtirish?", answer: "Katta rasmlarni preload qilish, server response vaqtini kamaytirish." },
  { id: 286, question: "Web Performance: CLS (Cumulative Layout Shift) nima?", answer: "Sahifa yuklanayotgan elementlarning kutilmagan 'sakrashi'." },
  { id: 287, question: "Core Web Vitals 'Good' ko'rsatkichlari?", answer: "LCP < 2.5s, FID < 100ms, CLS < 0.1." },
  { id: 288, question: "Hydration Mismatch sabablari?", answer: "Date.now(), Math.random() yoki brauzer-specific (window) kodlarni noto'g'ri ishlatish." },
  { id: 289, question: "BFF (Backend for Frontend) nima?", answer: "Frontend uchun maxsus moslashtirilgan o'rtadagi server/qatlam." },
  { id: 290, question: "Isomorphic JavaScript nima?", answer: "Ham serverda, ham mijozda bir xil ishlaydigan kod." },
  { id: 291, question: "Micro-frontends 'Iframe' usuli afzalligi?", answer: "To'liq izolyatsiya (JS va CSS bir-biriga ta'sir qilmaydi)." },
  { id: 292, question: "Module Federation 'Shared dependencies' nima?", answer: "Bir xil kutubxonalarni (masalan React) qayta-qayta yuklamaslik." },
  { id: 293, question: "Static Site Generation (SSG) vs Pre-rendering?", answer: "Pre-rendering kengroq tushuncha, SSG uning bir turi." },
  { id: 294, question: "Next.js 'API Routes' qachon kerak?", answer: "Frontend ichida backend funktsiyalarini (masalan Email yuborish) yozish uchun." },
  { id: 295, question: "Next.js 'Streaming' nima?", answer: "HTML-ni bo'laklarga bo'lib, tayyor bo'lishi bilan foydalanuvchiga yuborish." },
  { id: 296, question: "T3 Stack nima?", answer: "Next.js, TypeScript, Tailwind, tRPC dan tashkil topgan zamonaviy stack." },
  { id: 297, question: "tRPC nima?", answer: "Server va Frontend o'rtasida turlarni (types) ulashish imkonini beruvchi kutubxona." },
  { id: 298, question: "Edge Caching nima?", answer: "Ma'lumotlarni foydalanuvchiga eng yaqin geografik nuqtada saqlash." },
  { id: 299, question: "Cold Start (Serverless) nima?", answer: "Serverless funktsiya ancha vaqt ishlatilmagandan so'ng birinchi marta yuklanishidagi kechikish." },
  { id: 300, question: "Hydration 'Bail out' nima?", answer: "Xato yuz berganda React-ning mijozda noldan render qilishga o'tishi." },
  { id: 301, question: "Next.js 'Server Components' keshini qanday tozalash (revalidate)?", answer: "revalidatePath() yoki revalidateTag() funktsiyalari orqali." },
  { id: 302, question: "Next.js 'Static Export' cheklovlari?", answer: "Server-side dynamic API-lar (cookies, headers) ishlamaydi." },
  { id: 303, question: "Image LCP: 'priority' atributi?", answer: "Asosiy rasmni eng birinchi yuklash uchun qo'yiladigan belgi." },
  { id: 304, question: "Next.js 'generateStaticParams' vazifasi?", answer: "Dinamik route-lar uchun build vaqtida qaysi ID-larni statik qilishni belgilash." },
  { id: 305, question: "Next.js 'Metadata' ob'ekti afzalligi?", answer: "Statik va Dinamik (generateMetadata) SEO teglarni oson boshqarish." },
  { id: 306, question: "Vercel Analytics nima beradi?", answer: "Real foydalanuvchilardagi Web Vitals ko'rsatkichlarini." },
  { id: 307, question: "Edge Config nima?", answer: "Global o'zgaruvchilarni (masalan, feature flags) millisekundlarda o'qish tizimi." },
  { id: 308, question: "Next.js 'Instrumentation' fayli?", answer: "Monitoring vositalarini (Sentry, OpenTelemetry) sozlash uchun." },
  { id: 309, question: "Next.js 'Form' komponenti (v15+)?", answer: "Prefetching va Client-side navigation bilan integratsiyalashgan form." },
  { id: 310, question: "React 'Action State' nima?", answer: "Form harakatlari natijasini (xato, muvaffaqiyat) boshqarish uchun yangi hook." },

  // --- Performance & Low-Level JS (311-360) ---
  { id: 311, question: "JS Engine: 'Parser' nima?", answer: "Kodni o'qib, uni 'Abstract Syntax Tree' (AST) ga aylantiruvchi qism." },
  { id: 312, question: "JS Engine: 'Ignition Interpreter' nima?", answer: "AST-ni bytecode-ga aylantirib, darrov ishga tushiruvchi qism." },
  { id: 313, question: "JS Engine: 'Turbofan Optimizer' nima?", answer: "Ko'p ishlatiladigan kodni optimallashtirilgan mashina kodiga o'tkazuvchi qism." },
  { id: 314, question: "Inline Caching nima?", answer: "Ob'ekt xususiyatlarini qidirishni tezlashtiruvchi JS dvigateli optimizatsiyasi." },
  { id: 315, question: "Hidden Classes (V8) nima?", answer: "Bir xil strukturadagi ob'ektlarni guruhlash orqali ularga kirishni tezlashtirish." },
  { id: 316, question: "De-optimization qachon yuz beradi?", answer: "Optimallashtirilgan funktsiyaga kutilmagan turdagi (type change) ma'lumot kelsa." },
  { id: 317, question: "Memory: 'Stack' vs 'Heap'?", answer: "Stack - oddiy qiymatlar va funktsiya chaqiriqlari. Heap - katta ob'ektlar va massivlar." },
  { id: 318, question: "Mark-and-Sweep algoritmi?", answer: "Garbage collector-ning xotirani tozalash bo'yicha asosiy algoritmi." },
  { id: 319, question: "Reference Counting nima va muammosi?", answer: "Ob'ektga necha kishi murojaat qilayotganini sanash. Muammosi - Circular references." },
  { id: 320, question: "Pre-parsing vs Full parsing?", answer: "Faqat kerakli funktsiyalarni to'liq o'qish orqali yuklanish tezligini oshirish." },
  { id: 321, question: "WebAssembly (Wasm) nima?", answer: "Brauzerda C++, Rust kabi tillarni JS-dan ancha tez ishlatish imkoniyati." },
  { id: 322, question: "SharedArrayBuffer nima?", answer: "Turli oqimlar (Workers) o'rtasida umumiy xotira maydonidan foydalanish." },
  { id: 323, question: "Atomic Operations JS-da?", answer: "Shared memory-da ma'lumotlar bilan ishlashda poyga holatini (race condition) oldini olish." },
  { id: 324, question: "V8: Scavenge (Minor GC)?", answer: "Yangi yaratilgan ob'ektlarni tez-tez tozalab turuvchi GC qismi." },
  { id: 325, question: "V8: Major GC (Full Mark-Compact)?", answer: "Eski va katta ob'ektlarni tozalaydigan, og'irroq GC jarayoni." },
  { id: 326, question: "Zero-copy patterns nima?", answer: "Ma'lumotlarni bir joydan boshqa joyga ko'chirmasdan ishlov berish usullari." },
  { id: 327, question: "SIMD (Single Instruction Multiple Data) nima?", answer: "Bir vaqtning o'zida ko'p ma'lumotlar ustida amal bajarish (grafika/AI uchun)." },
  { id: 328, question: "JS Engine: Bytecode nima?", answer: "Mashina kodi va Yuqori darajali kod o'rtasidagi oraliq kod." },
  { id: 329, question: "Tail Call Optimization (TCO) JS-da bormi?", answer: "Faqat Safari (Webkit) brauzerida to'liq amalga oshirilgan." },
  { id: 330, question: "Proxy ob'ekti nima?", answer: "Ob'ekt amallarini (get, set) tutib olish va o'zgartirish uchun oraliq qatlam." },
  { id: 331, question: "Reflect API nima?", answer: "Proxy bilan ishlashda default amallarni bajarish uchun yordamchi API." },
  { id: 332, question: "Iterator vs Generator?", answer: "Iterator - keyingi elementni beradi. Generator - iteratorni yaratishning oson yo'li." },
  { id: 333, question: "Async Iterators (for-await-of)?", answer: "Asinxron ma'lumot oqimlari (stream) ustida aylanish." },
  { id: 334, question: "BigInt ma'lumot turi cheklovi?", answer: "Oddiy Number bilan to'g'ridan-to'g'ri qo'shib bo'lmaydi (math farqi)." },
  { id: 335, question: "Coalescing assignment (??=)?", answer: "Qiymat null/undefined bo'lsa yangi qiymat berish." },
  { id: 336, question: "WeakRef nima?", answer: "Ob'ektni GC-dan saqlab qolmagan holda unga murojaat qilish." },
  { id: 337, question: "FinalizationRegistry nima?", answer: "Ob'ekt xotiradan o'chirilganda callback chaqirish." },
  { id: 338, question: "Structured Clone API nima?", answer: "Ob'ektni xavfsiz va chuqur (deep) nusxalashning yangi brauzer usuli." },
  { id: 339, question: "Top-level Await nima?", answer: "Async funktsiya ichida bo'lmasdan ham await ishlatish (modul darajasida)." },
  { id: 340, question: "Import Maps nima?", answer: "Brauzerga modullarni qayerdan yuklashni o'rgatuvchi JSON schema." },
  { id: 341, question: "Web Cryptography API nima?", answer: "Brauzerda xavfsiz hash, shifrlash va raqamli imzo amallari." },
  { id: 342, question: "Service Worker Update Cycle?", answer: "Installing -> Waiting -> Activating." },
  { id: 343, question: "Push API vs Notification API?", answer: "Push - serverdan xabar kelishi. Notification - xabarni foydalanuvchiga ko'rsatish." },
  { id: 344, question: "Background Sync API nima?", answer: "Internet ulanganda orqa fonda ma'lumotlarni yuborish." },
  { id: 345, question: "Cache Storage API nima?", answer: "Request/Response juftliklarini keshda saqlash (Service worker uchun)." },
  { id: 346, question: "Beacon API nima?", answer: "Sahifa yopilayotganda kichik ma'lumotlarni (analitika) kafolatli yuborish." },
  { id: 347, question: "Broadcast Channel API nima?", answer: "Bitta domendagi turli tablar/oynalar o'rtasida ma'lumot almashish." },
  { id: 348, question: "Permissions API nima?", answer: "Kamera, Geolocation kabi ruxsatlar holatini tekshirish." },
  { id: 349, question: "File System Access API nima?", answer: "Brauzer orqali foydalanuvchi fayllarini o'qish va yozish (ruxsat bilan)." },
  { id: 350, question: "Web Bluetooth API nima?", answer: "Brauzer orqali Bluetooth qurilmalariga ulanish." },
  { id: 351, question: "Web Share API nima?", answer: "Mobil qurilmalardagi 'Share' menyusini ochish." },
  { id: 352, question: "Payment Request API nima?", answer: "To'lov ma'lumotlarini brauzer orqali xavfsiz yig'ish." },
  { id: 353, question: "Web Speech API nima?", answer: "Ovozni matnga va matnni ovozga aylantirish." },
  { id: 354, question: "GamePad API nima?", answer: "Joystik va boshqa o'yin kontrollerlarini brauzerda ishlatish." },
  { id: 355, question: "Presentation API nima?", answer: "Veb sahifani proektor yoki televizorga uzatish." },
  { id: 356, question: "Sensor APIs (Gyroscope, Accelerometer)?", answer: "Qurilma datchiklaridan ma'lumot olish." },
  { id: 357, question: "Web HID API nima?", answer: "Nostandart kiritish qurilmalari (USB-gadgets) bilan ishlash." },
  { id: 358, question: "Web Serial API nima?", answer: "Arduino kabi qurilmalar bilan Serial port orqali bog'lanish." },
  { id: 359, question: "Direct Sockets API nima?", answer: "TCP/UDP ulanishlarni o'rnatish (cheklangan muhitda)." },
  { id: 360, question: "Trusted Types API nima?", answer: "XSS hujumlarini oldini olish uchun DOM-ga faqat 'tozalangan' stringlarni yuborish." },

  // --- Security & Auth (361-400) ---
  { id: 361, question: "JWT Refresh Token nega kerak?", answer: "Access token muddati qisqa bo'ladi, uni yangilash uchun xavfsizroq Refresh token kerak." },
  { id: 362, question: "CSRF Token qanday ishlaydi?", answer: "Har bir so'rovga server tomonidan berilgan maxsus kod qo'shiladi (fake so'rovni aniqlash uchun)." },
  { id: 363, question: "Secure/HttpOnly Cookies nima?", answer: "HttpOnly - JS orqali o'qib bo'lmaydi. Secure - faqat HTTPS orqali yuboriladi." },
  { id: 364, question: "SameSite Cookie atributlari?", answer: "Strict, Lax, None - kross-sayt so'rovlarida cookie yuborilishini boshqaradi." },
  { id: 365, question: "HSTS (Strict Transport Security) nima?", answer: "Brauzerga saytga faqat HTTPS orqali kirishni buyurish." },
  { id: 366, question: "Subresource Integrity (SRI) nima?", answer: "CDN-dan yuklanayotgan script o'zgarmaganini hash orqali tekshirish." },
  { id: 367, question: "OpenID Connect (OIDC) nima?", answer: "OAuth 2.0 ustiga qurilgan identifikatsiya qatlami." },
  { id: 368, question: "RBAC (Role Based Access Control) nima?", answer: "Rollarga (Admin, User) qarab tizimga kirishni cheklash." },
  { id: 369, question: "ABAC (Attribute Based Access Control) nima?", answer: "Atributlar (vaqt, joylashuv, ID) asosida kirishni boshqarish." },
  { id: 370, question: "Rate Limiting nima?", answer: "Ma'lum vaqt ichida so'rovlar sonini cheklash (DDoS va brute-force dan himoya)." },
  { id: 371, question: "SQL Injection Frontend-da qanday oldi olinadi?", answer: "Inputlarni tozalash (sanitization) va backendda 'prepared statements' ishlatish." },
  { id: 372, question: "Man-in-the-Middle (MITM) nima?", answer: "Suhbatni (ma'lumot almashishni) yashirincha o'rtada kuzatish yoki o'zgartirish." },
  { id: 373, question: "Phishing nima?", answer: "Foydalanuvchini aldab maxfiy ma'lumotlarini olish (soxta saytlar orqali)." },
  { id: 374, question: "Social Engineering nima?", answer: "Texnik emas, psixologik usullar bilan ma'lumotlarni o'g'irlash." },
  { id: 375, question: "Password Hashing (Bcrypt/Argon2)?", answer: "Parollarni bazada ochiq emas, qaytarib bo'lmaydigan kodlangan holda saqlash." },
  { id: 376, question: "Salt nima?", answer: "Parol xeshiga qo'shiladigan tasodifiy string (Rainbow table hujumidan himoya)." },
  { id: 377, question: "Multi-Factor Authentication (MFA) usullari?", answer: "SMS, Email, Authenticator App (TOTP), Hardware keys (Yubikey)." },
  { id: 378, question: "Fingerprinting (Browser) nima?", answer: "Brauzer sozlamalari, shriftlar, datchiklar orqali foydalanuvchini 'tanish'." },
  { id: 379, question: "DuckDuckGo/Brave nega xavfsiz deb hisoblanadi?", answer: "Ular kuzatuvchi (tracker) scriptlarni bloklaydi va ma'lumot yig'maydi." },
  { id: 380, question: "Privacy Policy (GDPR) nima?", answer: "Foydalanuvchi ma'lumotlarini yig'ish va qayta ishlash bo'yicha Yevropa qonun-qoidalari." },

  // --- Testing & Quality (381-420) ---
  { id: 381, question: "Cypress vs Playwright?", answer: "Playwright tezroq, ko'proq brauzerlarni qo'llaydi va parallel testlashda kuchliroq." },
  { id: 382, question: "Jest vs Vitest?", answer: "Vitest Vite asosida ishlaydi va zamonaviy ESM loyihalarida ancha tezroq." },
  { id: 383, question: "Testing Library falsafasi?", answer: "Kodni emas, foydalanuvchi interfeysni qanday ko'rishini test qilish." },
  { id: 384, question: "Visual Regression Testing nima?", answer: "UI o'zgarganda piksellar darajasida farqni aniqlash." },
  { id: 385, question: "Fuzz Testing nima?", answer: "Dasturga tasodifiy, noto'g'ri ma'lumotlar berib xatolarni topish." },
  { id: 386, question: "Mutation Testing nima?", answer: "Kodingizni ataylab o'zgartirib, testlaringiz o'sha 'xatoni' topa olishini tekshirish." },
  { id: 387, question: "Static Analysis (ESLint/Prettier)?", answer: "Kodni ishga tushirmasdan turib xatolar va stilni tekshirish." },
  { id: 388, question: "Code Coverage nima?", answer: "Kodingizning necha foizi testlar bilan qamrab olingani ko'rsatkichi." },
  { id: 389, question: "Smoke Testing nima?", answer: "Dasturning eng muhim qismlari ishlashini tezkor tekshirish." },
  { id: 390, question: "Regression Testing nima?", answer: "Yangi qo'shilgan kod eski funksiyalarni buzmaganini tekshirish." },
  { id: 391, question: "Load Testing nima?", answer: "Tizim bir vaqtda ko'p foydalanuvchini ko'tara olishini tekshirish." },
  { id: 392, question: "Stress Testing nima?", answer: "Tizimni 'o'lish' nuqtasigacha qiynash va qanday tiklanishini ko'rish." },
  { id: 393, question: "A/B Testing nima?", answer: "Ikki xil UI versiyasini foydalanuvchilarga ko'rsatib, qaysi biri yaxshi natija berishini aniqlash." },
  { id: 394, question: "Usability Testing nima?", answer: "Real odamlar dasturni ishlatishda qanchalik qiynalishini kuzatish." },
  { id: 395, question: "A11y Testing vositalari?", answer: "axe-core, Lighthouse Accessibility, Screen readers." },
  { id: 396, question: "Performance Budget nima?", answer: "JS/CSS fayl o'lchami yoki yuklanish vaqti uchun qo'yilgan qat'iy limitlar." },
  { id: 397, question: "Dead Code Elimination nima?", answer: "Hech qachon ishlamaydigan (unreachable) kodlarni o'chirish." },
  { id: 398, question: "Cyclomatic Complexity nima?", answer: "Kodning murakkablik darajasi (if/loop-lar soni)." },
  { id: 399, question: "Bus Factor nima?", answer: "Loyiha to'xtab qolmasligi uchun necha kishi bilimga ega bo'lishi kerakligi (xavf o'lchovi)." },
  { id: 400, question: "Chaos Engineering nima?", answer: "Tizimga ataylab buzilishlar (serverni o'chirish) kiritib, uning chidamliligini tekshirish." },

  // --- Architecture & Patterns (401-440) ---
  { id: 401, question: "Serverless Architecture nima?", answer: "Server boshqaruvini Cloud provayderga (AWS Lambda, Vercel) topshirish." },
  { id: 402, question: "Edge Computing nima?", answer: "Hisob-kitoblarni markaziy serverda emas, foydalanuvchiga yaqin 'edge' nuqtalarda bajarish." },
  { id: 403, question: "Micro-services vs Monolith?", answer: "Monolith - hamma narsa bir joyda. Micro-services - mustaqil servislar to'plami." },
  { id: 404, question: "Event-Sourcing nima?", answer: "Hozirgi holatni emas, barcha o'zgarishlar tarixini (events) saqlash." },
  { id: 405, question: "CQRS (Command Query Responsibility Segregation)?", answer: "O'qish va yozish amallarini alohida modellarga ajratish." },
  { id: 406, question: "Hexagonal Architecture (Ports and Adapters)?", answer: "Biznes mantiqni tashqi dunyodan (DB, UI) to'liq izolyatsiya qilish." },
  { id: 407, question: "Clean Architecture (Uncle Bob)?", answer: "Kodning qatlamlarga (Entities, Use Cases, Adapters) qat'iy ajratilishi." },
  { id: 408, question: "DDD (Domain Driven Design) nima?", answer: "Dasturni biznes sohasidagi terminlar va mantiq asosida loyihalash." },
  { id: 409, question: "Service Mesh nima?", answer: "Microservislar o'rtasidagi aloqani boshqaruvchi infratuzilma qatlami." },
  { id: 410, question: "Observer Pattern amaliy misoli?", answer: "JS-dagi addEventListener yoki RxJS-dagi Observables." },
  { id: 411, question: "Strategy Pattern nima?", answer: "Bir xil vazifani bajaruvchi turli algoritmlarni (masalan, turli to'lov usullari) almashtirish imkoniyati." },
  { id: 112, question: "Factory Pattern nima?", answer: "Ob'ektlarni yaratish mantiqini yashirish va faqat interfeys berish." },
  { id: 413, question: "Singleton Pattern xavfi?", answer: "Global state yaratishi va testlashni qiyinlashtirishi." },
  { id: 414, question: "Adapter Pattern nima?", answer: "Bir interfeysni boshqasiga moslashtirish (wrap qilish)." },
  { id: 415, question: "Proxy Pattern nima?", answer: "Ob'ektga kirishni nazorat qilish yoki kesh qo'shish uchun oraliq ob'ekt." },
  { id: 416, question: "Facade Pattern nima?", answer: "Murakkab tizim uchun soddalashtirilgan interfeys taqdim etish." },
  { id: 417, question: "Decorator Pattern nima?", answer: "Ob'ektga uning klassini o'zgartirmasdan qo'shimcha vazifa yuklash." },
  { id: 418, question: "State Pattern nima?", answer: "Ob'ektning holatiga qarab uning o'zini tutishi o'zgarishi." },
  { id: 419, question: "Chain of Responsibility nima?", answer: "So'rovni bir nechta handler-lar orqali navbat bilan o'tkazish." },
  { id: 420, question: "Iterator Pattern nima?", answer: "To'plam ichki tuzilishini bilmagan holda uning elementlarini birma-bir o'qish." },
  { id: 421, question: "Flyweight Pattern nima?", answer: "Bir xil ma'lumotlarni ko'p ob'ektlar o'rtasida ulashish orqali xotirani tejash." },
  { id: 422, question: "Composite Pattern nima?", answer: "Daraxtsimon strukturalarni (masalan DOM) bir xil interfeys bilan boshqarish." },
  { id: 423, question: "Mediator Pattern nima?", answer: "Ob'ektlar o'rtasidagi to'g'ridan-to'g'ri bog'liqlikni kamaytirish uchun markaziy bog'lovchi." },
  { id: 424, question: "Memento Pattern nima?", answer: "Ob'ektning oldingi holatiga qaytish (undo) imkoniyatini yaratish." },
  { id: 425, question: "Visitor Pattern nima?", answer: "Strukturani o'zgartirmasdan uning elementlari ustida yangi amallar bajarish." },
  { id: 426, question: "Layered Architecture nima?", answer: "Presentation, Business, Data Access qatlamlariga bo'lish." },
  { id: 427, question: "Peer-to-Peer (P2P) nima?", answer: "Markaziy serversiz, qurilmalar o'zaro to'g'ridan-to'g'ri bog'lanishi." },
  { id: 428, question: "Pub/Sub vs Observer?", answer: "Pub/Sub-da ular bir-birini tanimaydi (Message Broker orqali), Observer-da taniydi." },
  { id: 429, question: "Inversion of Control (IoC) nima?", answer: "Dastur oqimini boshqarishni frameworkga yoki konteynerga topshirish." },
  { id: 430, question: "Dependency Lookup vs Injection?", answer: "Lookup - ob'ekt o'zi qidiradi. Injection - tashqaridan beriladi." },
  { id: 431, question: "Server-side Proxy nima?", answer: "So'rovlarni backendga yashirincha yo'naltirish (API key-larni yashirish uchun)." },
  { id: 432, question: "Load Balancer algoritmlari?", answer: "Round Robin, Least Connections, IP Hash." },
  { id: 433, question: "Database Sharding nima?", answer: "Bazani bir nechta serverlarga bo'lib yuborish." },
  { id: 434, question: "Database Replication nima?", answer: "Ma'lumotlar nusxasini boshqa serverda (Read replica) saqlash." },
  { id: 435, question: "CAP Theorem nima?", answer: "Consistency, Availability, Partition Tolerance - bazada uchtasidan faqat ikkitasini tanlash mumkin." },
  { id: 436, question: "Vertical vs Horizontal Scaling?", answer: "Vertical - bitta serverni kuchaytirish. Horizontal - ko'p server qo'shish." },
  { id: 437, question: "CDN (Content Delivery Network) qanday ishlaydi?", answer: "Resurslarni dunyo bo'ylab tarqalgan serverlarda keshlab foydalanuvchiga yaqinlashtiradi." },
  { id: 438, question: "Web Hooks nima?", answer: "Hodisa sodir bo'lganda bir tizimdan ikkinchi tizimga yuboriladigan HTTP POST so'rovi." },
  { id: 439, question: "Event Loop bloklanishi (Starvation) nima?", answer: "Sinxron og'ir kod tufayli asinxron vazifalar navbati kelmasligi." },
  { id: 440, question: "Single Page Application (SPA) kamchiligi?", answer: "SEO qiyinligi, katta initial bundle o'lchami." },

  // --- Miscellaneous & Soft Skills (441-500) ---
  { id: 441, question: "Semantic Versioning 2.0 qoidalari?", answer: "Breaking change (Major), New feature (Minor), Bug fix (Patch)." },
  { id: 442, question: "Git: Cherry-pick nima?", answer: "Boshqa branch-dagi faqat bitta commit-ni o'z branchiga olib o'tish." },
  { id: 443, question: "Git: Stash nima?", answer: "Chala ishlarni vaqtincha saqlab, branch-ni tozalash." },
  { id: 444, question: "Git: Squashing nima?", answer: "Bir nechta commit-larni bitta commit-ga birlashtirish." },
  { id: 445, question: "Git: Reflog nima?", answer: "Git-da o'chib ketgan commit yoki branch-larni qayta topish uchun jurnal." },
  { id: 446, question: "Markdown nima?", answer: "Matnlarni formatlash uchun yengil va ommabop sintaksis." },
  { id: 447, question: "Yarn vs NPM vs PNPM?", answer: "PNPM disk xotirasini tejash va tezlik bo'yicha eng kuchlisi." },
  { id: 448, question: "Lock fayllar (package-lock.json) nega kerak?", answer: "Hamma dasturchilarda bir xil versiyadagi kutubxonalar o'rnatilishini ta'minlash." },
  { id: 449, question: "Peer Dependencies nima?", answer: "Kutubxona ishlashi uchun zarur bo'lgan, lekin foydalanuvchi o'zi o'rnatishi kerak bo'lgan paketlar." },
  { id: 450, question: "Semantic Commit Messages nima?", answer: "feat: ..., fix: ..., docs: ... kabi standart nomlash." },
  { id: 451, question: "Bus Factor-ni qanday oshirish mumkin?", answer: "Hujjatlashtirish (docs), Pair programming va Code reviews orqali." },
  { id: 452, question: "Rubber Duck Debugging nima?", answer: "Xatoni kimgadir (yoki o'yinchoq o'rdakka) tushuntirib berish orqali yechim topish." },
  { id: 453, question: "Pareto Principle (80/20) dasturlashda?", answer: "80% natija 20% koddan yoki 80% xatolar 20% moduldan keladi." },
  { id: 454, question: "YAGNI (You Ain't Gonna Need It) nima?", answer: "Kerak bo'lmagan funktsiyalarni 'kelajakda kerak bo'ladi' deb yozmaslik." },
  { id: 455, question: "KISS (Keep It Simple, Stupid) nima?", answer: "Yechimni iloji boricha sodda va tushunarli qilish." },
  { id: 456, question: "Premature Optimization nima?", answer: "Xali muammo bo'lmagan joyni optimallashtirishga vaqt sarflash (xavfli)." },
  { id: 457, question: "Bus Factor nima?", answer: "Loyiha bilimlarining jamoa bo'ylab qanchalik taqsimlangani." },
  { id: 458, question: "Technical Debt qachon foydali?", answer: "MVP-ni tezroq chiqarish va bozorni tekshirish kerak bo'lganda." },
  { id: 459, question: "Imposter Syndrome nima?", answer: "O'z bilimidan shubhalanish va 'soxta' mutaxassisdek his qilish (ko'p uchraydi)." },
  { id: 460, question: "Burnout (Charchash) oldini olish?", answer: "Work-life balance, dam olish va qiziqarli hobbi." },
  { id: 461, question: "Pair Programming afzalligi?", answer: "Kamroq xatolar, bilimlarni almashish va tezroq yechim." },
  { id: 462, question: "Code Ownership nima?", answer: "Koddagi ma'lum qismlar uchun mas'uliyat his qilish." },
  { id: 463, question: "Agile: Sprint nima?", answer: "Vazifalarni bajarish uchun belgilangan 1-4 haftalik davr." },
  { id: 464, question: "Scrum: Daily Stand-up nima?", answer: "Har kuni 15 daqiqalik holat so'rash yig'ilishi." },
  { id: 465, question: "Kanban vs Scrum?", answer: "Kanban - uzluksiz oqim. Scrum - qat'iy davrlar (sprints)." },
  { id: 466, question: "MVP (Minimum Viable Product) nima?", answer: "Faqat eng muhim funktsiyalarga ega bo'lgan mahsulot versiyasi." },
  { id: 467, question: "Product-Market Fit nima?", answer: "Mahsulotning bozor talablariga to'liq mos kelishi." },
  { id: 468, question: "Open Source-ga hissa qo'shish afzalligi?", answer: "Tajriba orttirish, networking va kuchli portfolio." },
  { id: 469, question: "Technical Writer nima qiladi?", answer: "Dasturiy mahsulotlar uchun texnik hujjatlar (documentation) yozadi." },
  { id: 470, question: "DevOps vs SRE (Site Reliability Engineering)?", answer: "SRE - bu DevOps falsafasining muhandislik orqali amalga oshirilgan varianti." },
  { id: 471, question: "Linux: 'chmod' nima?", answer: "Fayl va papkalarga ruxsatlarni (read, write, execute) o'zgartirish." },
  { id: 472, question: "Linux: 'grep' nima?", answer: "Matn ichidan qidirish vositasi." },
  { id: 473, question: "Docker: Image vs Container?", answer: "Image - shablon (diska). Container - o'sha shablondan yaratilgan tirik jarayon." },
  { id: 474, question: "Kubernetes (K8s) nima?", answer: "Konteynerlarni avtomatlashtirilgan boshqaruv tizimi (orchestration)." },
  { id: 475, question: "Nginx nima?", answer: "Yuqori samaradorli veb-server va Reverse Proxy." },
  { id: 476, question: "Load Balancing 'Sticky Sessions' nima?", answer: "Foydalanuvchini har doim bitta serverga yo'naltirish (session saqlash uchun)." },
  { id: 477, question: "Infrastructure as Code (IaC) nima?", answer: "Infratuzilmani (serverlar) kod orqali boshqarish (Terraform, Ansible)." },
  { id: 478, question: "Server Monitoring (Prometheus/Grafana)?", answer: "Server holati (CPU, RAM) va xatolarini vizual kuzatish." },
  { id: 479, question: "Logging: ELK Stack nima?", answer: "Elasticsearch, Logstash, Kibana - loglarni yig'ish va tahlil qilish." },
  { id: 480, question: "Green Computing nima?", answer: "Dasturlashda energiya sarfini (xotira/hisob-kitob) kamaytirish orqali tabiatni asrash." },
  { id: 481, question: "Micro-interactions nima?", answer: "UI-dagi kichik, yoqimli animatsiyalar (masalan, like tugmasi)." },
  { id: 482, question: "Design System nima?", answer: "Komponentlar, qoidalar va vizual tildan tashkil topgan umumiy tizim." },
  { id: 483, question: "UX: Fitts's Law nima?", answer: "Tugma qanchalik katta va yaqin bo'lsa, uni bosish shunchalik oson." },
  { id: 484, question: "UX: Hick's Law nima?", answer: "Tanlovlar soni ko'paysa, qaror qabul qilish vaqti ham ko'payadi." },
  { id: 485, question: "Color Accessibility (Contrast)?", answer: "Matn va fon rangi ko'rishda qiyinchilik tug'dirmasligi (ratio 4.5:1)." },
  { id: 486, question: "Typography: Serif vs Sans-serif?", answer: "Serif - uchi 'oyoqli' (kitoblar uchun), Sans-serif - silliq (ekranlar uchun)." },
  { id: 487, question: "SVG Optimizers (SVGO)?", answer: "SVG fayllar ichidagi ortiqcha kodlarni o'chirib hajmini kichraytirish." },
  { id: 488, question: "Web performance: Gzip vs Deflate?", answer: "Gzip hozirda eng ommabop va samarali siqish usuli." },
  { id: 489, question: "Critical Request Chain nima?", answer: "Sahifa render bo'lishi uchun ketma-ket yuklanishi shart bo'lgan resurslar." },
  { id: 490, question: "First Contentful Paint (FCP) nima?", answer: "Ekranda birinchi marta biron bir kontent (matn/rasm) ko'ringan vaqt." },
  { id: 491, question: "Time to Interactive (TTI) nima?", answer: "Sahifa to'liq interaktiv bo'lgan vaqt." },
  { id: 492, question: "Total Blocking Time (TBT) nima?", answer: "FCP va TTI orasidagi asosiy oqim bloklangan vaqt." },
  { id: 493, question: "Speed Index nima?", answer: "Sahifa vizual ravishda qanchalik tez to'lishi ko'rsatkichi." },
  { id: 494, question: "Memory Management 'Heap Snapshot' nima?", answer: "Xotira holatini rasmga olib, leak-larni qidirish." },
  { id: 495, question: "Browser 'Paint Profiler' nima?", answer: "Qaysi elementlar eng ko'p render vaqtini olayotganini ko'rish." },
  { id: 496, question: "Deadlock nima?", answer: "Ikki jarayon bir-birini resurs bo'shatishini kutib qolishi (abadiy kutish)." },
  { id: 497, question: "Race Condition nima?", answer: "Ikki amal kutilmagan tartibda bajarilib, noto'g'ri natija berishi." },
  { id: 498, question: "Idempotency nima?", answer: "Bir amalni ko'p marta bajarish natijani o'zgartirmasligi (masalan, GET so'rovi)." },
  { id: 499, question: "Stateless vs Stateful?", answer: "Stateless - har bir so'rov mustaqil. Stateful - oldingi so'rovlar tarixini eslab qoladi." },
  { id: 500, question: "Frontend Developer kelajagi?", answer: "Sun'iy intellekt bilan hamkorlikda ishlash, WebGL/WebGPU va yanada murakkabroq web-ilovalar." }
];
